Predict Titanic Survival
The RMS Titanic set sail on its maiden voyage in 1912, crossing the Atlantic from Southampton, England to New York City. The ship never completed the voyage, sinking to the bottom of the Atlantic Ocean after hitting an iceberg, bringing down 1,502 of 2,224 passengers onboard.

In this project you will create a Logistic Regression model that predicts which passengers survived the sinking of the Titanic, based on features like age and class.

The data we will be using for training our model is provided by Kaggle. Feel free to make the model better on your own and submit it to the Kaggle Titanic competition!

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
# Load the passenger data
passengers = pd.read_csv('train.csv')
print(passengers)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
5              6         0       3
6              7         0       1
7              8         0       3
8              9         1       3
9             10         1       2
10            11         1       3
11            12         1       1
12            13         0       3
13            14         0       3
14            15         0       3
15            16         1       2
16            17         0       3
17            18         1       2
18            19         0       3
19            20         1       3
20            21         0       2
21            22         1       2
22            23         1       3
23            24         1       1
24            25         0       3
25            26         1       3
26            27         0       3
27            28         0       1
28            29         1       3
29            30         0       3
..           ...       ...     ...
861          862         0       2
862          863         1       1
863          864         0       3
864          865         0       2
865          866         1       2
866          867         1       2
867          868         0       1
868          869         0       3
869          870         1       3
870          871         0       3
871          872         1       1
872          873         0       1
873          874         0       3
874          875         1       2
875          876         1       3
876          877         0       3
877          878         0       3
878          879         0       3
879          880         1       1
880          881         1       2
881          882         0       3
882          883         0       3
883          884         0       2
884          885         0       3
885          886         0       3
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
5                                     Moran, Mr. James    male   NaN      0
6                              McCarthy, Mr. Timothy J    male  54.0      0
7                       Palsson, Master. Gosta Leonard    male   2.0      3
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1
11                            Bonnell, Miss. Elizabeth  female  58.0      0
12                      Saundercock, Mr. William Henry    male  20.0      0
13                         Andersson, Mr. Anders Johan    male  39.0      1
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
16                                Rice, Master. Eugene    male   2.0      4
17                        Williams, Mr. Charles Eugene    male   NaN      0
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1
19                             Masselmani, Mrs. Fatima  female   NaN      0
20                                Fynney, Mr. Joseph J    male  35.0      0
21                               Beesley, Mr. Lawrence    male  34.0      0
22                         McGowan, Miss. Anna "Annie"  female  15.0      0
23                        Sloper, Mr. William Thompson    male  28.0      0
24                       Palsson, Miss. Torborg Danira  female   8.0      3
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1
26                             Emir, Mr. Farred Chehab    male   NaN      0
27                      Fortune, Mr. Charles Alexander    male  19.0      3
28                       O'Dwyer, Miss. Ellen "Nellie"  female   NaN      0
29                                 Todoroff, Mr. Lalio    male   NaN      0
..                                                 ...     ...   ...    ...
861                        Giles, Mr. Frederick Edward    male  21.0      1
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0      0
863                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN      8
864                             Gill, Mr. John William    male  24.0      0
865                           Bystrom, Mrs. (Karolina)  female  42.0      0
866                       Duran y More, Miss. Asuncion  female  27.0      1
867               Roebling, Mr. Washington Augustus II    male  31.0      0
868                        van Melkebeke, Mr. Philemon    male   NaN      0
869                    Johnson, Master. Harold Theodor    male   4.0      1
870                                  Balkic, Mr. Cerin    male  26.0      0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
872                           Carlsson, Mr. Frans Olof    male  33.0      0
873                        Vander Cruyssen, Mr. Victor    male  47.0      0
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
876                      Gustafsson, Mr. Alfred Ossian    male  20.0      0
877                               Petroff, Mr. Nedelio    male  19.0      0
878                                 Laleff, Mr. Kristo    male   NaN      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
881                                 Markun, Mr. Johann    male  33.0      0
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
883                      Banfield, Mr. Frederick James    male  28.0      0
884                             Sutehall, Mr. Henry Jr    male  25.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket      Fare        Cabin Embarked
0        0         A/5 21171    7.2500          NaN        S
1        0          PC 17599   71.2833          C85        C
2        0  STON/O2. 3101282    7.9250          NaN        S
3        0            113803   53.1000         C123        S
4        0            373450    8.0500          NaN        S
5        0            330877    8.4583          NaN        Q
6        0             17463   51.8625          E46        S
7        1            349909   21.0750          NaN        S
8        2            347742   11.1333          NaN        S
9        0            237736   30.0708          NaN        C
10       1           PP 9549   16.7000           G6        S
11       0            113783   26.5500         C103        S
12       0         A/5. 2151    8.0500          NaN        S
13       5            347082   31.2750          NaN        S
14       0            350406    7.8542          NaN        S
15       0            248706   16.0000          NaN        S
16       1            382652   29.1250          NaN        Q
17       0            244373   13.0000          NaN        S
18       0            345763   18.0000          NaN        S
19       0              2649    7.2250          NaN        C
20       0            239865   26.0000          NaN        S
21       0            248698   13.0000          D56        S
22       0            330923    8.0292          NaN        Q
23       0            113788   35.5000           A6        S
24       1            349909   21.0750          NaN        S
25       5            347077   31.3875          NaN        S
26       0              2631    7.2250          NaN        C
27       2             19950  263.0000  C23 C25 C27        S
28       0            330959    7.8792          NaN        Q
29       0            349216    7.8958          NaN        S
..     ...               ...       ...          ...      ...
861      0             28134   11.5000          NaN        S
862      0             17466   25.9292          D17        S
863      2          CA. 2343   69.5500          NaN        S
864      0            233866   13.0000          NaN        S
865      0            236852   13.0000          NaN        S
866      0     SC/PARIS 2149   13.8583          NaN        C
867      0          PC 17590   50.4958          A24        S
868      0            345777    9.5000          NaN        S
869      1            347742   11.1333          NaN        S
870      0            349248    7.8958          NaN        S
871      1             11751   52.5542          D35        S
872      0               695    5.0000  B51 B53 B55        S
873      0            345765    9.0000          NaN        S
874      0         P/PP 3381   24.0000          NaN        C
875      0              2667    7.2250          NaN        C
876      0              7534    9.8458          NaN        S
877      0            349212    7.8958          NaN        S
878      0            349217    7.8958          NaN        S
879      1             11767   83.1583          C50        C
880      1            230433   26.0000          NaN        S
881      0            349257    7.8958          NaN        S
882      0              7552   10.5167          NaN        S
883      0  C.A./SOTON 34068   10.5000          NaN        S
884      0   SOTON/OQ 392076    7.0500          NaN        S
885      5            382652   29.1250          NaN        Q
886      0            211536   13.0000          NaN        S
887      0            112053   30.0000          B42        S
888      2        W./C. 6607   23.4500          NaN        S
889      0            111369   30.0000         C148        C
890      0            370376    7.7500          NaN        Q

[891 rows x 12 columns]

Given the saying, "women and children first," Sex and Age seem like good features to predict survival. Let's map the text values in the Sex column to a numerical value. Update Sex such that all values female are replaced with 1 and all values male are replaced with 0.

In [5]:
# Update sex column to numerical
passengers.Sex = np.where(passengers.Sex =="female", 1,0)
print(passengers)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
5              6         0       3
6              7         0       1
7              8         0       3
8              9         1       3
9             10         1       2
10            11         1       3
11            12         1       1
12            13         0       3
13            14         0       3
14            15         0       3
15            16         1       2
16            17         0       3
17            18         1       2
18            19         0       3
19            20         1       3
20            21         0       2
21            22         1       2
22            23         1       3
23            24         1       1
24            25         0       3
25            26         1       3
26            27         0       3
27            28         0       1
28            29         1       3
29            30         0       3
..           ...       ...     ...
861          862         0       2
862          863         1       1
863          864         0       3
864          865         0       2
865          866         1       2
866          867         1       2
867          868         0       1
868          869         0       3
869          870         1       3
870          871         0       3
871          872         1       1
872          873         0       1
873          874         0       3
874          875         1       2
875          876         1       3
876          877         0       3
877          878         0       3
878          879         0       3
879          880         1       1
880          881         1       2
881          882         0       3
882          883         0       3
883          884         0       2
884          885         0       3
885          886         0       3
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1
2                               Heikkinen, Miss. Laina    1  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1
4                             Allen, Mr. William Henry    0  35.0      0
5                                     Moran, Mr. James    0   NaN      0
6                              McCarthy, Mr. Timothy J    0  54.0      0
7                       Palsson, Master. Gosta Leonard    0   2.0      3
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1
11                            Bonnell, Miss. Elizabeth    1  58.0      0
12                      Saundercock, Mr. William Henry    0  20.0      0
13                         Andersson, Mr. Anders Johan    0  39.0      1
14                Vestrom, Miss. Hulda Amanda Adolfina    1  14.0      0
15                    Hewlett, Mrs. (Mary D Kingcome)     1  55.0      0
16                                Rice, Master. Eugene    0   2.0      4
17                        Williams, Mr. Charles Eugene    0   NaN      0
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...    1  31.0      1
19                             Masselmani, Mrs. Fatima    1   NaN      0
20                                Fynney, Mr. Joseph J    0  35.0      0
21                               Beesley, Mr. Lawrence    0  34.0      0
22                         McGowan, Miss. Anna "Annie"    1  15.0      0
23                        Sloper, Mr. William Thompson    0  28.0      0
24                       Palsson, Miss. Torborg Danira    1   8.0      3
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...    1  38.0      1
26                             Emir, Mr. Farred Chehab    0   NaN      0
27                      Fortune, Mr. Charles Alexander    0  19.0      3
28                       O'Dwyer, Miss. Ellen "Nellie"    1   NaN      0
29                                 Todoroff, Mr. Lalio    0   NaN      0
..                                                 ...  ...   ...    ...
861                        Giles, Mr. Frederick Edward    0  21.0      1
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...    1  48.0      0
863                  Sage, Miss. Dorothy Edith "Dolly"    1   NaN      8
864                             Gill, Mr. John William    0  24.0      0
865                           Bystrom, Mrs. (Karolina)    1  42.0      0
866                       Duran y More, Miss. Asuncion    1  27.0      1
867               Roebling, Mr. Washington Augustus II    0  31.0      0
868                        van Melkebeke, Mr. Philemon    0   NaN      0
869                    Johnson, Master. Harold Theodor    0   4.0      1
870                                  Balkic, Mr. Cerin    0  26.0      0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    1  47.0      1
872                           Carlsson, Mr. Frans Olof    0  33.0      0
873                        Vander Cruyssen, Mr. Victor    0  47.0      0
874              Abelson, Mrs. Samuel (Hannah Wizosky)    1  28.0      1
875                   Najib, Miss. Adele Kiamie "Jane"    1  15.0      0
876                      Gustafsson, Mr. Alfred Ossian    0  20.0      0
877                               Petroff, Mr. Nedelio    0  19.0      0
878                                 Laleff, Mr. Kristo    0   NaN      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    1  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)    1  25.0      0
881                                 Markun, Mr. Johann    0  33.0      0
882                       Dahlberg, Miss. Gerda Ulrika    1  22.0      0
883                      Banfield, Mr. Frederick James    0  28.0      0
884                             Sutehall, Mr. Henry Jr    0  25.0      0
885               Rice, Mrs. William (Margaret Norton)    1  39.0      0
886                              Montvila, Rev. Juozas    0  27.0      0
887                       Graham, Miss. Margaret Edith    1  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    1   NaN      1
889                              Behr, Mr. Karl Howell    0  26.0      0
890                                Dooley, Mr. Patrick    0  32.0      0

     Parch            Ticket      Fare        Cabin Embarked
0        0         A/5 21171    7.2500          NaN        S
1        0          PC 17599   71.2833          C85        C
2        0  STON/O2. 3101282    7.9250          NaN        S
3        0            113803   53.1000         C123        S
4        0            373450    8.0500          NaN        S
5        0            330877    8.4583          NaN        Q
6        0             17463   51.8625          E46        S
7        1            349909   21.0750          NaN        S
8        2            347742   11.1333          NaN        S
9        0            237736   30.0708          NaN        C
10       1           PP 9549   16.7000           G6        S
11       0            113783   26.5500         C103        S
12       0         A/5. 2151    8.0500          NaN        S
13       5            347082   31.2750          NaN        S
14       0            350406    7.8542          NaN        S
15       0            248706   16.0000          NaN        S
16       1            382652   29.1250          NaN        Q
17       0            244373   13.0000          NaN        S
18       0            345763   18.0000          NaN        S
19       0              2649    7.2250          NaN        C
20       0            239865   26.0000          NaN        S
21       0            248698   13.0000          D56        S
22       0            330923    8.0292          NaN        Q
23       0            113788   35.5000           A6        S
24       1            349909   21.0750          NaN        S
25       5            347077   31.3875          NaN        S
26       0              2631    7.2250          NaN        C
27       2             19950  263.0000  C23 C25 C27        S
28       0            330959    7.8792          NaN        Q
29       0            349216    7.8958          NaN        S
..     ...               ...       ...          ...      ...
861      0             28134   11.5000          NaN        S
862      0             17466   25.9292          D17        S
863      2          CA. 2343   69.5500          NaN        S
864      0            233866   13.0000          NaN        S
865      0            236852   13.0000          NaN        S
866      0     SC/PARIS 2149   13.8583          NaN        C
867      0          PC 17590   50.4958          A24        S
868      0            345777    9.5000          NaN        S
869      1            347742   11.1333          NaN        S
870      0            349248    7.8958          NaN        S
871      1             11751   52.5542          D35        S
872      0               695    5.0000  B51 B53 B55        S
873      0            345765    9.0000          NaN        S
874      0         P/PP 3381   24.0000          NaN        C
875      0              2667    7.2250          NaN        C
876      0              7534    9.8458          NaN        S
877      0            349212    7.8958          NaN        S
878      0            349217    7.8958          NaN        S
879      1             11767   83.1583          C50        C
880      1            230433   26.0000          NaN        S
881      0            349257    7.8958          NaN        S
882      0              7552   10.5167          NaN        S
883      0  C.A./SOTON 34068   10.5000          NaN        S
884      0   SOTON/OQ 392076    7.0500          NaN        S
885      5            382652   29.1250          NaN        Q
886      0            211536   13.0000          NaN        S
887      0            112053   30.0000          B42        S
888      2        W./C. 6607   23.4500          NaN        S
889      0            111369   30.0000         C148        C
890      0            370376    7.7500          NaN        Q

[891 rows x 12 columns]

In [6]:
# Fill the nan values in the age column
print(passengers['Age'].values)
passengers['Age'].fillna(round(passengers['Age'].mean()),inplace=True)

[22.   38.   26.   35.   35.     nan 54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.     nan 31.     nan 35.   34.   15.   28.
  8.   38.     nan 19.     nan   nan 40.     nan   nan 66.   28.   42.
   nan 21.   18.   14.   40.   27.     nan  3.   19.     nan   nan   nan
   nan 18.    7.   21.   49.   29.   65.     nan 21.   28.5   5.   11.
 22.   38.   45.    4.     nan   nan 29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.     nan   nan  0.83 30.   22.   29.     nan 28.
 17.   33.   16.     nan 23.   24.   29.   20.   46.   26.   59.     nan
 71.   23.   34.   34.   28.     nan 21.   33.   37.   28.   21.     nan
 38.     nan 47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.     nan 32.5  32.5  54.   12.     nan 24.     nan 45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.     nan 22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5    nan 51.
 16.   30.     nan   nan 44.   40.   26.   17.    1.    9.     nan 45.
   nan 28.   61.    4.    1.   21.   56.   18.     nan 50.   30.   36.
   nan   nan  9.    1.    4.     nan   nan 45.   40.   36.   32.   19.
 19.    3.   44.   58.     nan 42.     nan 24.   28.     nan 34.   45.5
 18.    2.   32.   26.   16.   40.   24.   35.   22.   30.     nan 31.
 27.   42.   32.   30.   16.   27.   51.     nan 38.   22.   19.   20.5
 18.     nan 35.   29.   59.    5.   24.     nan 44.    8.   19.   33.
   nan   nan 29.   22.   30.   44.   25.   24.   37.   54.     nan 29.
 62.   30.   41.   29.     nan 30.   35.   50.     nan  3.   52.   40.
   nan 36.   16.   25.   58.   35.     nan 25.   41.   37.     nan 63.
 45.     nan  7.   35.   65.   28.   16.   19.     nan 33.   30.   22.
 42.   22.   26.   19.   36.   24.   24.     nan 23.5   2.     nan 50.
   nan   nan 19.     nan   nan  0.92   nan 17.   30.   30.   24.   18.
 26.   28.   43.   26.   24.   54.   31.   40.   22.   27.   30.   22.
   nan 36.   61.   36.   31.   16.     nan 45.5  38.   16.     nan   nan
 29.   41.   45.   45.    2.   24.   28.   25.   36.   24.   40.     nan
  3.   42.   23.     nan 15.   25.     nan 28.   22.   38.     nan   nan
 40.   29.   45.   35.     nan 30.   60.     nan   nan 24.   25.   18.
 19.   22.    3.     nan 22.   27.   20.   19.   42.    1.   32.   35.
   nan 18.    1.   36.     nan 17.   36.   21.   28.   23.   24.   22.
 31.   46.   23.   28.   39.   26.   21.   28.   20.   34.   51.    3.
 21.     nan   nan   nan 33.     nan 44.     nan 34.   18.   30.   10.
   nan 21.   29.   28.   18.     nan 28.   19.     nan 32.   28.     nan
 42.   17.   50.   14.   21.   24.   64.   31.   45.   20.   25.   28.
   nan  4.   13.   34.    5.   52.   36.     nan 30.   49.     nan 29.
 65.     nan 50.     nan 48.   34.   47.   48.     nan 38.     nan 56.
   nan  0.75   nan 38.   33.   23.   22.     nan 34.   29.   22.    2.
  9.     nan 50.   63.   25.     nan 35.   58.   30.    9.     nan 21.
 55.   71.   21.     nan 54.     nan 25.   24.   17.   21.     nan 37.
 16.   18.   33.     nan 28.   26.   29.     nan 36.   54.   24.   47.
 34.     nan 36.   32.   30.   22.     nan 44.     nan 40.5  50.     nan
 39.   23.    2.     nan 17.     nan 30.    7.   45.   30.     nan 22.
 36.    9.   11.   32.   50.   64.   19.     nan 33.    8.   17.   27.
   nan 22.   22.   62.   48.     nan 39.   36.     nan 40.   28.     nan
   nan 24.   19.   29.     nan 32.   62.   53.   36.     nan 16.   19.
 34.   39.     nan 32.   25.   39.   54.   36.     nan 18.   47.   60.
 22.     nan 35.   52.   47.     nan 37.   36.     nan 49.     nan 49.
 24.     nan   nan 44.   35.   36.   30.   27.   22.   40.   39.     nan
   nan   nan 35.   24.   34.   26.    4.   26.   27.   42.   20.   21.
 21.   61.   57.   21.   26.     nan 80.   51.   32.     nan  9.   28.
 32.   31.   41.     nan 20.   24.    2.     nan  0.75 48.   19.   56.
   nan 23.     nan 18.   21.     nan 18.   24.     nan 32.   23.   58.
 50.   40.   47.   36.   20.   32.   25.     nan 43.     nan 40.   31.
 70.   31.     nan 18.   24.5  18.   43.   36.     nan 27.   20.   14.
 60.   25.   14.   19.   18.   15.   31.    4.     nan 25.   60.   52.
 44.     nan 49.   42.   18.   35.   18.   25.   26.   39.   45.   42.
 22.     nan 24.     nan 48.   29.   52.   19.   38.   27.     nan 33.
  6.   17.   34.   50.   27.   20.   30.     nan 25.   25.   29.   11.
   nan 23.   23.   28.5  48.   35.     nan   nan   nan 36.   21.   24.
 31.   70.   16.   30.   19.   31.    4.    6.   33.   23.   48.    0.67
 28.   18.   34.   33.     nan 41.   20.   36.   16.   51.     nan 30.5
   nan 32.   24.   48.   57.     nan 54.   18.     nan  5.     nan 43.
 13.   17.   29.     nan 25.   25.   18.    8.    1.   46.     nan 16.
   nan   nan 25.   39.   49.   31.   30.   30.   34.   31.   11.    0.42
 27.   31.   39.   18.   39.   33.   26.   39.   35.    6.   30.5    nan
 23.   31.   43.   10.   52.   27.   38.   27.    2.     nan   nan  1.
   nan 62.   15.    0.83   nan 23.   18.   39.   21.     nan 32.     nan
 20.   16.   30.   34.5  17.   42.     nan 35.   28.     nan  4.   74.
  9.   16.   44.   18.   45.   51.   24.     nan 41.   21.   48.     nan
 24.   42.   27.   31.     nan  4.   26.   47.   33.   47.   28.   15.
 20.   19.     nan 56.   25.   33.   22.   28.   25.   39.   27.   19.
   nan 26.   32.  ]

Given the strict class system onboard the Titanic, let's utilize the Pclass column

In [7]:
# Create a first class column
passengers['FirstClass'] = np.where(passengers['Pclass']==1,1.0,0.0)

# Create a second class column
passengers['SecondClass'] = np.where(passengers['Pclass']==2,1.0,0.0)
print(passengers)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
5              6         0       3
6              7         0       1
7              8         0       3
8              9         1       3
9             10         1       2
10            11         1       3
11            12         1       1
12            13         0       3
13            14         0       3
14            15         0       3
15            16         1       2
16            17         0       3
17            18         1       2
18            19         0       3
19            20         1       3
20            21         0       2
21            22         1       2
22            23         1       3
23            24         1       1
24            25         0       3
25            26         1       3
26            27         0       3
27            28         0       1
28            29         1       3
29            30         0       3
..           ...       ...     ...
861          862         0       2
862          863         1       1
863          864         0       3
864          865         0       2
865          866         1       2
866          867         1       2
867          868         0       1
868          869         0       3
869          870         1       3
870          871         0       3
871          872         1       1
872          873         0       1
873          874         0       3
874          875         1       2
875          876         1       3
876          877         0       3
877          878         0       3
878          879         0       3
879          880         1       1
880          881         1       2
881          882         0       3
882          883         0       3
883          884         0       2
884          885         0       3
885          886         0       3
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1
2                               Heikkinen, Miss. Laina    1  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1
4                             Allen, Mr. William Henry    0  35.0      0
5                                     Moran, Mr. James    0  30.0      0
6                              McCarthy, Mr. Timothy J    0  54.0      0
7                       Palsson, Master. Gosta Leonard    0   2.0      3
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1
10                     Sandstrom, Miss. Marguerite Rut    1   4.0      1
11                            Bonnell, Miss. Elizabeth    1  58.0      0
12                      Saundercock, Mr. William Henry    0  20.0      0
13                         Andersson, Mr. Anders Johan    0  39.0      1
14                Vestrom, Miss. Hulda Amanda Adolfina    1  14.0      0
15                    Hewlett, Mrs. (Mary D Kingcome)     1  55.0      0
16                                Rice, Master. Eugene    0   2.0      4
17                        Williams, Mr. Charles Eugene    0  30.0      0
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...    1  31.0      1
19                             Masselmani, Mrs. Fatima    1  30.0      0
20                                Fynney, Mr. Joseph J    0  35.0      0
21                               Beesley, Mr. Lawrence    0  34.0      0
22                         McGowan, Miss. Anna "Annie"    1  15.0      0
23                        Sloper, Mr. William Thompson    0  28.0      0
24                       Palsson, Miss. Torborg Danira    1   8.0      3
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...    1  38.0      1
26                             Emir, Mr. Farred Chehab    0  30.0      0
27                      Fortune, Mr. Charles Alexander    0  19.0      3
28                       O'Dwyer, Miss. Ellen "Nellie"    1  30.0      0
29                                 Todoroff, Mr. Lalio    0  30.0      0
..                                                 ...  ...   ...    ...
861                        Giles, Mr. Frederick Edward    0  21.0      1
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...    1  48.0      0
863                  Sage, Miss. Dorothy Edith "Dolly"    1  30.0      8
864                             Gill, Mr. John William    0  24.0      0
865                           Bystrom, Mrs. (Karolina)    1  42.0      0
866                       Duran y More, Miss. Asuncion    1  27.0      1
867               Roebling, Mr. Washington Augustus II    0  31.0      0
868                        van Melkebeke, Mr. Philemon    0  30.0      0
869                    Johnson, Master. Harold Theodor    0   4.0      1
870                                  Balkic, Mr. Cerin    0  26.0      0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)    1  47.0      1
872                           Carlsson, Mr. Frans Olof    0  33.0      0
873                        Vander Cruyssen, Mr. Victor    0  47.0      0
874              Abelson, Mrs. Samuel (Hannah Wizosky)    1  28.0      1
875                   Najib, Miss. Adele Kiamie "Jane"    1  15.0      0
876                      Gustafsson, Mr. Alfred Ossian    0  20.0      0
877                               Petroff, Mr. Nedelio    0  19.0      0
878                                 Laleff, Mr. Kristo    0  30.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    1  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)    1  25.0      0
881                                 Markun, Mr. Johann    0  33.0      0
882                       Dahlberg, Miss. Gerda Ulrika    1  22.0      0
883                      Banfield, Mr. Frederick James    0  28.0      0
884                             Sutehall, Mr. Henry Jr    0  25.0      0
885               Rice, Mrs. William (Margaret Norton)    1  39.0      0
886                              Montvila, Rev. Juozas    0  27.0      0
887                       Graham, Miss. Margaret Edith    1  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    1  30.0      1
889                              Behr, Mr. Karl Howell    0  26.0      0
890                                Dooley, Mr. Patrick    0  32.0      0

     Parch            Ticket      Fare        Cabin Embarked  FirstClass  \
0        0         A/5 21171    7.2500          NaN        S         0.0
1        0          PC 17599   71.2833          C85        C         1.0
2        0  STON/O2. 3101282    7.9250          NaN        S         0.0
3        0            113803   53.1000         C123        S         1.0
4        0            373450    8.0500          NaN        S         0.0
5        0            330877    8.4583          NaN        Q         0.0
6        0             17463   51.8625          E46        S         1.0
7        1            349909   21.0750          NaN        S         0.0
8        2            347742   11.1333          NaN        S         0.0
9        0            237736   30.0708          NaN        C         0.0
10       1           PP 9549   16.7000           G6        S         0.0
11       0            113783   26.5500         C103        S         1.0
12       0         A/5. 2151    8.0500          NaN        S         0.0
13       5            347082   31.2750          NaN        S         0.0
14       0            350406    7.8542          NaN        S         0.0
15       0            248706   16.0000          NaN        S         0.0
16       1            382652   29.1250          NaN        Q         0.0
17       0            244373   13.0000          NaN        S         0.0
18       0            345763   18.0000          NaN        S         0.0
19       0              2649    7.2250          NaN        C         0.0
20       0            239865   26.0000          NaN        S         0.0
21       0            248698   13.0000          D56        S         0.0
22       0            330923    8.0292          NaN        Q         0.0
23       0            113788   35.5000           A6        S         1.0
24       1            349909   21.0750          NaN        S         0.0
25       5            347077   31.3875          NaN        S         0.0
26       0              2631    7.2250          NaN        C         0.0
27       2             19950  263.0000  C23 C25 C27        S         1.0
28       0            330959    7.8792          NaN        Q         0.0
29       0            349216    7.8958          NaN        S         0.0
..     ...               ...       ...          ...      ...         ...
861      0             28134   11.5000          NaN        S         0.0
862      0             17466   25.9292          D17        S         1.0
863      2          CA. 2343   69.5500          NaN        S         0.0
864      0            233866   13.0000          NaN        S         0.0
865      0            236852   13.0000          NaN        S         0.0
866      0     SC/PARIS 2149   13.8583          NaN        C         0.0
867      0          PC 17590   50.4958          A24        S         1.0
868      0            345777    9.5000          NaN        S         0.0
869      1            347742   11.1333          NaN        S         0.0
870      0            349248    7.8958          NaN        S         0.0
871      1             11751   52.5542          D35        S         1.0
872      0               695    5.0000  B51 B53 B55        S         1.0
873      0            345765    9.0000          NaN        S         0.0
874      0         P/PP 3381   24.0000          NaN        C         0.0
875      0              2667    7.2250          NaN        C         0.0
876      0              7534    9.8458          NaN        S         0.0
877      0            349212    7.8958          NaN        S         0.0
878      0            349217    7.8958          NaN        S         0.0
879      1             11767   83.1583          C50        C         1.0
880      1            230433   26.0000          NaN        S         0.0
881      0            349257    7.8958          NaN        S         0.0
882      0              7552   10.5167          NaN        S         0.0
883      0  C.A./SOTON 34068   10.5000          NaN        S         0.0
884      0   SOTON/OQ 392076    7.0500          NaN        S         0.0
885      5            382652   29.1250          NaN        Q         0.0
886      0            211536   13.0000          NaN        S         0.0
887      0            112053   30.0000          B42        S         1.0
888      2        W./C. 6607   23.4500          NaN        S         0.0
889      0            111369   30.0000         C148        C         1.0
890      0            370376    7.7500          NaN        Q         0.0

     SecondClass
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
5            0.0
6            0.0
7            0.0
8            0.0
9            1.0
10           0.0
11           0.0
12           0.0
13           0.0
14           0.0
15           1.0
16           0.0
17           1.0
18           0.0
19           0.0
20           1.0
21           1.0
22           0.0
23           0.0
24           0.0
25           0.0
26           0.0
27           0.0
28           0.0
29           0.0
..           ...
861          1.0
862          0.0
863          0.0
864          1.0
865          1.0
866          1.0
867          0.0
868          0.0
869          0.0
870          0.0
871          0.0
872          0.0
873          0.0
874          1.0
875          0.0
876          0.0
877          0.0
878          0.0
879          0.0
880          1.0
881          0.0
882          0.0
883          1.0
884          0.0
885          0.0
886          1.0
887          0.0
888          0.0
889          0.0
890          0.0

[891 rows x 14 columns]


Now that we have cleaned our data, let's select the columns we want to build our model on. Select columns Sex, Age, FirstClass, and SecondClass and store them in a variable named features. Select column Survived and store it a variable named survival

In [8]:
# Select the desired features
features = passengers[['Sex', 'Age', 'FirstClass', 'SecondClass']]
Survived  = passengers['Survived']

In [9]:
# Perform train, test, split
f_train,f_test,s_train,s_test = train_test_split(features,Survived)

In [10]:
# Scale the feature data so it has mean = 0 and standard deviation = 1
m = StandardScaler()
f_train = m.fit_transform(f_train)
f_test = m.transform(f_test)

In [11]:
# Create and train the model
model = LogisticRegression()
model.fit(f_train,s_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
# Score the model on the train data
print(model.score(f_train,s_train))

# Score the model on the test data
print(model.score(f_test,s_test))

0.7859281437125748
0.7713004484304933

In [13]:
# Analyze the coefficients. Which feature is most important in predicting survival on the sinking of the Titanic?
print(model.coef_)

[[ 1.27917974 -0.48157728  1.11964694  0.53794477]]

In [14]:
# Sample passenger features
Jack = np.array([0.0,20.0,0.0,0.0])
Rose = np.array([1.0,17.0,1.0,0.0])
You = np.array([1.0,23,0.0,0.0])

In [15]:
# Combine passenger arrays
sample_passengers =np.array([Jack, Rose, You]) 

# Scale the sample passenger features
sample_passengers = m.transform(sample_passengers)
print(sample_passengers)

[[-0.74396799 -0.75499366 -0.57043565 -0.50327259]
 [ 1.34414385 -0.981486    1.75304613 -0.50327259]
 [ 1.34414385 -0.52850133 -0.57043565 -0.50327259]]

In [16]:
# Make survival predictions!
print(model.predict(sample_passengers))
print(model.predict_proba(sample_passengers))

[0 1 1]
[[0.89943849 0.10056151]
 [0.03952016 0.96047984]
 [0.40830045 0.59169955]]